route:
  receiver: 'default'
  group_by: ["service", "alertname", "severity"]
  group_wait: 2m
  group_interval: 5m
  repeat_interval: 2h

receivers:
  - name: 'default'

templates:
  - '/etc/alertmanager/templates/message.template'
