version: "3.8"
services:
  db:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  indexer:
    image: indexer
    environment:
      - RPC_URL=https://mainnet.base.org
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - redis
    build:
      context: idxr/friendmex/.

volumes:
  db:
    driver: local
