version: "3.8"
services:
  db:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  idxr:
    image: idxr
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
      - REDIS_URL=redis:6379
    ports:
      - "8085:8080"
    command: ["npm", "run", "start:idxr"]
    depends_on:
      - db
      - redis
    build:
      context: api/.

  api:
    image: api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
    ports:
      - "8084:8080"
    command: ["npm", "run", "start"]
    depends_on:
      - db
    build:
      context: api/.

  sync:
    image: sync
    command: ["npm", "run", "start:sync"]
    environment:
      MNEMONIC_FILE: /run/secrets/mnemonic.txt
      MONITORED_ADDRESS: "0xd85eff2d610132d507ece73e1f37df82774a8d47"
    secrets:
      - mnemonic.txt
    build:
      context: api/.

volumes:
  db:
    driver: local

secrets:
  mnemonic.txt:
    file: ./mnemonic.txt
