version: "3.8"
services:
  db:
    image: postgres:15.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  idxr:
    image: idxr
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
    ports:
      - "127.0.0.1:8085:8080"
    command: ["npm", "run", "start:idxr"]
    depends_on:
      - db
    restart: always
    build:
      context: api/.

  aggr:
    image: aggr
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
    command: ["npm", "run", "start:aggr"]
    depends_on:
      - db
    restart: always
    build:
      context: api/.

  api:
    image: api
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
      - REDIS_HOST=redis
    ports:
      - "8084:8080"
    command: ["npm", "run", "start"]
    depends_on:
      - db
      - redis
    restart: always
    build:
      context: api/.

  prometheus:
    image: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - alertmanager
    restart: always
    build:
      context: prometheus/.
    volumes:
      - promdata:/data

  alertmanager:
    image: alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    restart: always
    build:
      context: alertmanager/.

  grafana:
    image: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
    restart: always
    build:
      context: grafana/.

  sscr:
    image: sscr
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?schema=postgres
      - REDIS_HOST=redis
    command: ["npm", "run", "start:sscr"]
    depends_on:
      - db
      - redis
    restart: always
    build:
      context: api/.

  sync:
    image: sync
    command: ["npm", "run", "start:sync"]
    environment:
      MNEMONIC_FILE: /run/secrets/mnemonic.txt
      MONITORED_ADDRESSES: "0x1b546a13875c83db8bab7ea4df760b13019a976c,0x1f5b68b914f7ad1afca4528b357827def2500f38,0x3ee9eda7d7ae365b47be8bfe67e07e27522aaf6a,0x5479f127a4d594208549c86f4b4903a1175a0311,0x9c1c9027f2e9194f00f8f732de9f36fdc1e225d6,0xa84bd0e9646170b91c75a999332954a15e4969b3,0xa8ba11db2901905c6ab49c1c86e69fd22081f68a,0xd85eff2d610132d507ece73e1f37df82774a8d47,0xef42b587e4a3d33f88fa499be1d80c676ff7a226,0xf0a5a3b09a919c7fe826ea0d9482e8d377952821,0xf9b7cf4be6f4cde37dd1a5b75187d431d94a4fcc"
    secrets:
      - mnemonic.txt
    restart: always
    build:
      context: api/.

volumes:
  db:
    driver: local
  promdata:
    driver: local

secrets:
  mnemonic.txt:
    file: ./mnemonic.txt
