groups:
  - name: monitoring
    rules:
      - alert: apiDown
        expr: |
          up{service="api"} < 1
        labels:
          severity: red
        annotations:
          summary: "the API is down"
