global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets:
          - api:8081
    relabel_configs:
      - target_label: service
        replacement: api

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/prometheus.rules.yml
