global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets:
          - api:8081
    relabel_configs:
      - target_label: service
        replacement: api
  - job_name: idxr-friendtech
    static_configs:
      - targets:
          - idxr-friendtech:8081
    relabel_configs:
      - target_label: service
        replacement: idxr-friendtech
  - job_name: idxr-frenbond
    static_configs:
      - targets:
          - idxr-frenbond:8081
    relabel_configs:
      - target_label: service
        replacement: idxr-frenbond
  - job_name: block-mainnet
    static_configs:
      - targets:
          - block-mainnet:8081
    relabel_configs:
      - target_label: service
        replacement: block-mainnet
  - job_name: block-goerli
    static_configs:
      - targets:
          - block-goerli:8081
    relabel_configs:
      - target_label: service
        replacement: block-goerli
  - job_name: sync
    static_configs:
      - targets:
          - sync:8081
    relabel_configs:
      - target_label: service
        replacement: sync
  - job_name: aggr
    static_configs:
      - targets:
          - aggr:8081
    relabel_configs:
      - target_label: service
        replacement: aggr
  - job_name: sscr
    static_configs:
      - targets:
          - sscr:8081
    relabel_configs:
      - target_label: service
        replacement: sscr

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - /etc/prometheus/prometheus.rules.yml
