apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: P1809F7CD0C75ACF3
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.2
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
  - name: postgres
    type: postgres
    url: db:5432
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 50
      maxIdleConns: 50
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
